version: "3.8"
services:
  postgres:
    image: postgres:latest
    volumes:
      - volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandbox

volumes:
  volume: {}
